import { Alert, Incident, PhishingSubmission, Report, DashboardStats, User } from "@/types";

export const MOCK_USER: User = {
  id: "usr_001",
  email: "admin@gmail.com",
  username: "admin",
  role: "soc_manager",
  is_active: true,
  is_mfa_enabled: false,
  last_login: new Date(Date.now() - 3_600_000).toISOString(),
  created_at: new Date(Date.now() - 90 * 86400_000).toISOString(),
};

const ago = (ms: number) => new Date(Date.now() - ms).toISOString();
const mins = (n: number) => n * 60_000;
const hrs  = (n: number) => n * 3_600_000;
const days = (n: number) => n * 86400_000;

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alrt_001", tenant_id: "t1", title: "Ransomware detected on FILESERVER01", description: "CryptoLocker variant identified by behavioral analysis. File encryption activity detected across shared drives.", severity: "critical", status: "in_progress", source: "edr", source_ref: "EDR-4821", risk_score: 97, ai_summary: "High-confidence ransomware attack. Immediate isolation required.", ai_recommendation: "1. Isolate host immediately\n2. Preserve memory dump\n3. Identify patient zero\n4. Restore from clean backup", mitre_tactics: ["Execution","Impact"], mitre_techniques: [{ id: "T1486", name: "Data Encrypted for Impact" }], iocs: [{ type: "hash", value: "a1b2c3d4e5f6789012345678901234ab", context: "Ransomware binary" }, { type: "domain", value: "cryptopay-c2.onion", context: "C2 server" }], is_ai_triaged: true, tags: ["ransomware", "critical-asset"], occurred_at: ago(hrs(2)), created_at: ago(hrs(2)), updated_at: ago(mins(30)),
  },
  {
    id: "alrt_002", tenant_id: "t1", title: "Mimikatz credential dumping on DC01", description: "LSASS memory access pattern consistent with Mimikatz tool detected on domain controller.", severity: "critical", status: "triaging", source: "edr", source_ref: "EDR-4822", risk_score: 95, ai_summary: "Credential harvesting from domain controller. Potential full domain compromise.", ai_recommendation: "Reset all domain admin passwords immediately", mitre_tactics: ["Credential Access", "Discovery"], mitre_techniques: [{ id: "T1003", name: "OS Credential Dumping" }], iocs: [{ type: "hash", value: "deadbeef1234567890abcdef12345678", context: "Mimikatz variant" }], is_ai_triaged: true, tags: ["credential-dumping", "apt"], occurred_at: ago(hrs(4)), created_at: ago(hrs(4)), updated_at: ago(hrs(1)),
  },
  {
    id: "alrt_003", tenant_id: "t1", title: "Lateral movement via SMB detected", description: "Unusual SMB traffic pattern indicating lateral movement from workstation WS-055 to multiple servers.", severity: "high", status: "escalated", source: "siem", source_ref: "SIEM-9901", risk_score: 88, ai_summary: "Active lateral movement campaign in progress. Multiple hosts potentially compromised.", ai_recommendation: "Block SMB traffic between workstations, segment network", mitre_tactics: ["Lateral Movement"], mitre_techniques: [{ id: "T1021.002", name: "SMB/Windows Admin Shares" }], iocs: [{ type: "ip", value: "10.0.5.55", context: "Source host" }, { type: "ip", value: "10.0.1.10", context: "DC reached" }], is_ai_triaged: true, tags: ["lateral-movement", "smb"], occurred_at: ago(hrs(6)), created_at: ago(hrs(6)), updated_at: ago(hrs(2)),
  },
  {
    id: "alrt_004", tenant_id: "t1", title: "Brute force attack on VPN concentrator", description: "1,200+ failed authentication attempts against VPN gateway from external IP in 5 minutes.", severity: "high", status: "new", source: "firewall", source_ref: "FW-3301", risk_score: 78, ai_summary: "Credential stuffing attack targeting VPN. Risk of successful breach if credentials reused.", ai_recommendation: "Block source IP, enable geo-blocking, enforce MFA", mitre_tactics: ["Initial Access", "Credential Access"], mitre_techniques: [{ id: "T1110", name: "Brute Force" }], iocs: [{ type: "ip", value: "185.220.101.47", context: "Tor exit node" }], is_ai_triaged: true, tags: ["brute-force", "vpn"], occurred_at: ago(hrs(1)), created_at: ago(hrs(1)), updated_at: null,
  },
  {
    id: "alrt_005", tenant_id: "t1", title: "Data exfiltration to cloud storage", description: "Large volume of sensitive files uploaded to personal Google Drive from corporate device.", severity: "high", status: "in_progress", source: "siem", source_ref: "SIEM-9902", risk_score: 85, ai_summary: "Potential insider threat or compromised account exfiltrating sensitive data.", ai_recommendation: "Block cloud storage access, initiate HR investigation", mitre_tactics: ["Exfiltration"], mitre_techniques: [{ id: "T1567", name: "Exfiltration Over Web Service" }], iocs: [{ type: "domain", value: "drive.google.com", context: "Exfil target" }], is_ai_triaged: false, tags: ["exfiltration", "insider-threat"], occurred_at: ago(hrs(3)), created_at: ago(hrs(3)), updated_at: ago(hrs(1)),
  },
  {
    id: "alrt_006", tenant_id: "t1", title: "Suspicious PowerShell encoded command", description: "Base64 encoded PowerShell command executed on multiple endpoints, downloading payload from remote server.", severity: "high", status: "new", source: "siem", source_ref: "SIEM-9903", risk_score: 82, ai_summary: "Stage-2 malware loader via PowerShell. Command pattern matches known APT toolset.", ai_recommendation: "Block PowerShell execution policy, investigate all affected hosts", mitre_tactics: ["Execution", "Defense Evasion"], mitre_techniques: [{ id: "T1059.001", name: "PowerShell" }, { id: "T1027", name: "Obfuscated Files" }], iocs: [{ type: "url", value: "http://185.234.219.11/stage2.ps1", context: "Payload URL" }], is_ai_triaged: true, tags: ["powershell", "malware"], occurred_at: ago(mins(45)), created_at: ago(mins(45)), updated_at: null,
  },
  {
    id: "alrt_007", tenant_id: "t1", title: "Active Directory enumeration detected", description: "LDAP queries consistent with BloodHound/SharpHound domain enumeration tool from user account.", severity: "high", status: "triaging", source: "siem", source_ref: "SIEM-9904", risk_score: 80, ai_summary: "Attacker mapping AD structure. Likely pre-movement recon phase.", ai_recommendation: "Identify compromised user account, check for privilege escalation", mitre_tactics: ["Discovery"], mitre_techniques: [{ id: "T1087", name: "Account Discovery" }], iocs: [{ type: "ip", value: "10.0.3.22", context: "Source workstation" }], is_ai_triaged: false, tags: ["ad-enum", "bloodhound"], occurred_at: ago(hrs(5)), created_at: ago(hrs(5)), updated_at: ago(hrs(2)),
  },
  {
    id: "alrt_008", tenant_id: "t1", title: "Cryptomining malware on AWS EC2 instance", description: "Unusual CPU spike (98%) on production EC2 instance with outbound connections to known mining pools.", severity: "high", status: "in_progress", source: "cloud", source_ref: "AWS-0012", risk_score: 72, ai_summary: "Cryptominer deployed on cloud infrastructure, consuming resources and increasing costs.", ai_recommendation: "Terminate affected instance, review IAM permissions, patch container escape vuln", mitre_tactics: ["Impact"], mitre_techniques: [{ id: "T1496", name: "Resource Hijacking" }], iocs: [{ type: "domain", value: "pool.minexmr.com", context: "Mining pool" }], is_ai_triaged: true, tags: ["cryptominer", "cloud"], occurred_at: ago(hrs(8)), created_at: ago(hrs(8)), updated_at: ago(hrs(3)),
  },
  {
    id: "alrt_009", tenant_id: "t1", title: "Phishing email campaign — executive impersonation", description: "Spear-phishing emails impersonating CEO sent to 47 employees requesting wire transfers.", severity: "high", status: "new", source: "email", source_ref: "EMAIL-5521", risk_score: 76, ai_summary: "Business Email Compromise attempt targeting finance team. High probability of financial loss.", ai_recommendation: "Quarantine all received emails, alert finance team, report to bank", mitre_tactics: ["Initial Access", "Social Engineering"], mitre_techniques: [{ id: "T1566.002", name: "Spearphishing Link" }], iocs: [{ type: "email", value: "ceo@company-corp.com", context: "Spoofed sender" }, { type: "domain", value: "company-corp.com", context: "Lookalike domain" }], is_ai_triaged: true, tags: ["phishing", "bec"], occurred_at: ago(mins(90)), created_at: ago(mins(90)), updated_at: null,
  },
  {
    id: "alrt_010", tenant_id: "t1", title: "Suspicious DNS query to known C2 domain", description: "Internal host communicating with domain matching Cobalt Strike beacon profile signature.", severity: "medium", status: "triaging", source: "siem", source_ref: "SIEM-9905", risk_score: 68, ai_summary: "Possible C2 communication channel established. Host may be compromised.", ai_recommendation: "Block DNS resolution, analyze host traffic, check for persistence", mitre_tactics: ["Command and Control"], mitre_techniques: [{ id: "T1071.004", name: "DNS" }], iocs: [{ type: "domain", value: "update-windows-cdn.com", context: "C2 domain" }, { type: "ip", value: "91.195.240.123", context: "Resolved C2 IP" }], is_ai_triaged: true, tags: ["c2", "cobalt-strike"], occurred_at: ago(hrs(7)), created_at: ago(hrs(7)), updated_at: ago(hrs(1)),
  },
  {
    id: "alrt_011", tenant_id: "t1", title: "Malicious macro in Office document", description: "Excel file with embedded macro downloaded from email, spawning cmd.exe child process.", severity: "medium", status: "resolved", source: "edr", source_ref: "EDR-4823", risk_score: 65, ai_summary: "Macro-based dropper successfully detected and quarantined before execution.", ai_recommendation: "Disable macros by policy, remediation complete", mitre_tactics: ["Execution"], mitre_techniques: [{ id: "T1137", name: "Office Application Startup" }], iocs: [{ type: "hash", value: "f0e1d2c3b4a5968778695a4b3c2d1e0f", context: "Malicious .xlsm" }], is_ai_triaged: true, tags: ["macro", "office"], occurred_at: ago(days(1)), created_at: ago(days(1)), updated_at: ago(hrs(20)),
  },
  {
    id: "alrt_012", tenant_id: "t1", title: "Port scan from internal IP — 10.0.2.15", description: "Internal workstation performing SYN scan against /24 subnet, probing ports 22, 80, 443, 3389.", severity: "medium", status: "new", source: "ids_ips", source_ref: "IDS-7712", risk_score: 55, ai_summary: "Internal reconnaissance activity. Could indicate lateral movement preparation.", ai_recommendation: "Identify the user on 10.0.2.15, check for unauthorized software", mitre_tactics: ["Discovery"], mitre_techniques: [{ id: "T1046", name: "Network Service Discovery" }], iocs: [{ type: "ip", value: "10.0.2.15", context: "Scanning host" }], is_ai_triaged: false, tags: ["port-scan", "recon"], occurred_at: ago(hrs(9)), created_at: ago(hrs(9)), updated_at: null,
  },
  {
    id: "alrt_013", tenant_id: "t1", title: "Multiple failed SSH logins on bastion host", description: "550 failed SSH authentication attempts from Tor exit node over 10 minutes on bastion host.", severity: "medium", status: "triaging", source: "siem", source_ref: "SIEM-9906", risk_score: 58, ai_summary: "Automated credential stuffing against SSH. Low risk if key-based auth enforced.", ai_recommendation: "Verify key-only auth, add Fail2ban rule, review bastion access logs", mitre_tactics: ["Credential Access"], mitre_techniques: [{ id: "T1110.004", name: "Credential Stuffing" }], iocs: [{ type: "ip", value: "51.83.202.54", context: "Tor exit node" }], is_ai_triaged: true, tags: ["ssh", "brute-force"], occurred_at: ago(hrs(11)), created_at: ago(hrs(11)), updated_at: ago(hrs(8)),
  },
  {
    id: "alrt_014", tenant_id: "t1", title: "Suspicious Azure AD sign-in from anomalous location", description: "Senior admin account logged in from Nigeria, 30 minutes after normal US-based login.", severity: "high", status: "escalated", source: "cloud", source_ref: "AZURE-0034", risk_score: 83, ai_summary: "Impossible travel detected. Account likely compromised.", ai_recommendation: "Force password reset, revoke all sessions, enable Conditional Access", mitre_tactics: ["Initial Access"], mitre_techniques: [{ id: "T1078", name: "Valid Accounts" }], iocs: [{ type: "ip", value: "41.206.23.17", context: "Nigerian IP" }], is_ai_triaged: true, tags: ["cloud", "impossible-travel", "aad"], occurred_at: ago(hrs(12)), created_at: ago(hrs(12)), updated_at: ago(hrs(4)),
  },
  {
    id: "alrt_015", tenant_id: "t1", title: "Anomalous after-hours data access", description: "Finance analyst account accessing large volume of payroll files at 3:47 AM on Saturday.", severity: "medium", status: "new", source: "siem", source_ref: "SIEM-9907", risk_score: 62, ai_summary: "Unusual access pattern suggesting insider threat or compromised account.", ai_recommendation: "Review file access logs, check if account is shared, verify with employee", mitre_tactics: ["Collection"], mitre_techniques: [{ id: "T1083", name: "File and Directory Discovery" }], iocs: [], is_ai_triaged: false, tags: ["insider-threat", "ueba"], occurred_at: ago(hrs(14)), created_at: ago(hrs(14)), updated_at: null,
  },
  {
    id: "alrt_016", tenant_id: "t1", title: "USB mass storage device on air-gapped system", description: "Unauthorized USB drive inserted on SCADA workstation in operational technology zone.", severity: "high", status: "new", source: "edr", source_ref: "EDR-4824", risk_score: 79, ai_summary: "Policy violation on critical OT system. Physical security incident possible.", ai_recommendation: "Review CCTV footage, confiscate device, inspect for malware", mitre_tactics: ["Initial Access"], mitre_techniques: [{ id: "T1091", name: "Replication Through Removable Media" }], iocs: [], is_ai_triaged: false, tags: ["usb", "ot-security"], occurred_at: ago(hrs(16)), created_at: ago(hrs(16)), updated_at: null,
  },
  {
    id: "alrt_017", tenant_id: "t1", title: "Web application SQL injection attempt", description: "300+ SQL injection payloads detected targeting customer portal login endpoint.", severity: "medium", status: "resolved", source: "ids_ips", source_ref: "WAF-2201", risk_score: 52, ai_summary: "Automated SQLi scan blocked by WAF. No successful queries detected.", ai_recommendation: "Review WAF rules, check application logs, patch any identified vulnerabilities", mitre_tactics: ["Initial Access"], mitre_techniques: [{ id: "T1190", name: "Exploit Public-Facing Application" }], iocs: [{ type: "ip", value: "103.45.67.89", context: "Attacker IP" }], is_ai_triaged: true, tags: ["sqli", "web"], occurred_at: ago(days(2)), created_at: ago(days(2)), updated_at: ago(days(1) + hrs(20)),
  },
  {
    id: "alrt_018", tenant_id: "t1", title: "Scheduled task created for persistence", description: "New scheduled task created by non-admin user running executable from temp directory.", severity: "medium", status: "triaging", source: "edr", source_ref: "EDR-4825", risk_score: 60, ai_summary: "Persistence mechanism installed. Investigate parent process and executable.", ai_recommendation: "Delete scheduled task, quarantine executable, investigate user account", mitre_tactics: ["Persistence"], mitre_techniques: [{ id: "T1053.005", name: "Scheduled Task" }], iocs: [{ type: "hash", value: "1122334455667788990011223344aabb", context: "Suspicious executable" }], is_ai_triaged: false, tags: ["persistence", "scheduled-task"], occurred_at: ago(days(1)), created_at: ago(days(1)), updated_at: ago(days(1)),
  },
  {
    id: "alrt_019", tenant_id: "t1", title: "DLL side-loading on finance workstation", description: "Legitimate signed binary loading malicious DLL from user-writable path on finance workstation.", severity: "critical", status: "new", source: "edr", source_ref: "EDR-4826", risk_score: 91, ai_summary: "Sophisticated evasion technique active. Attacker using trusted binary to proxy execution.", ai_recommendation: "Isolate workstation immediately, full forensic investigation required", mitre_tactics: ["Defense Evasion", "Persistence"], mitre_techniques: [{ id: "T1574.002", name: "DLL Side-Loading" }], iocs: [{ type: "hash", value: "aabbccddeeff00112233445566778899", context: "Malicious DLL" }], is_ai_triaged: true, tags: ["dll-sideloading", "evasion"], occurred_at: ago(mins(20)), created_at: ago(mins(20)), updated_at: null,
  },
  {
    id: "alrt_020", tenant_id: "t1", title: "Kerberoasting attack detected", description: "Service account tickets requested for 12 SPNs in 30 seconds — classic Kerberoasting pattern.", severity: "high", status: "new", source: "siem", source_ref: "SIEM-9908", risk_score: 77, ai_summary: "Kerberoasting attack for offline password cracking. Privileged service accounts at risk.", ai_recommendation: "Use Group Managed Service Accounts (gMSA), audit SPN accounts, reset passwords", mitre_tactics: ["Credential Access"], mitre_techniques: [{ id: "T1558.003", name: "Kerberoasting" }], iocs: [{ type: "ip", value: "10.0.4.88", context: "Attacking host" }], is_ai_triaged: false, tags: ["kerberoasting", "active-directory"], occurred_at: ago(mins(60)), created_at: ago(mins(60)), updated_at: null,
  },
  {
    id: "alrt_021", tenant_id: "t1", title: "Outdated OpenSSL detected — CVE-2024-5535", description: "Production web server running OpenSSL 1.1.1 with known critical vulnerability allowing RCE.", severity: "high", status: "new", source: "siem", source_ref: "SCAN-0089", risk_score: 74, ai_summary: "Critical unpatched vulnerability on internet-facing system. Patch immediately.", ai_recommendation: "Emergency patch to OpenSSL 3.x, consider temporary WAF rule", mitre_tactics: ["Initial Access"], mitre_techniques: [{ id: "T1190", name: "Exploit Public-Facing Application" }], iocs: [], is_ai_triaged: false, tags: ["vulnerability", "openssl", "patch"], occurred_at: ago(days(3)), created_at: ago(days(3)), updated_at: null,
  },
  {
    id: "alrt_022", tenant_id: "t1", title: "Domain admin account created outside change window", description: "New domain admin account 'svc_backup' created at 2:15 AM outside approved change control window.", severity: "critical", status: "triaging", source: "siem", source_ref: "SIEM-9909", risk_score: 93, ai_summary: "Unauthorized privileged account creation. Possible persistence mechanism by attacker.", ai_recommendation: "Disable account immediately, audit who created it, review all actions", mitre_tactics: ["Persistence", "Privilege Escalation"], mitre_techniques: [{ id: "T1136.002", name: "Create Account: Domain Account" }], iocs: [], is_ai_triaged: true, tags: ["account-creation", "privilege-escalation"], occurred_at: ago(hrs(18)), created_at: ago(hrs(18)), updated_at: ago(hrs(6)),
  },
  {
    id: "alrt_023", tenant_id: "t1", title: "Unauthorized RDP session from external IP", description: "RDP session opened from external IP to internal server bypassing VPN — possible firewall misconfiguration.", severity: "high", status: "in_progress", source: "firewall", source_ref: "FW-3302", risk_score: 86, ai_summary: "Direct external RDP access indicates firewall rule misconfiguration or breach.", ai_recommendation: "Block external RDP immediately, audit firewall rules, investigate session activity", mitre_tactics: ["Initial Access", "Lateral Movement"], mitre_techniques: [{ id: "T1021.001", name: "Remote Desktop Protocol" }], iocs: [{ type: "ip", value: "212.47.234.191", context: "External attacker IP" }], is_ai_triaged: true, tags: ["rdp", "remote-access"], occurred_at: ago(hrs(10)), created_at: ago(hrs(10)), updated_at: ago(hrs(2)),
  },
  {
    id: "alrt_024", tenant_id: "t1", title: "Low: Expired SSL certificate on internal service", description: "Internal monitoring dashboard SSL certificate expired 3 days ago.", severity: "low", status: "new", source: "siem", source_ref: "MONITOR-0012", risk_score: 22, ai_summary: "Minor certificate hygiene issue. Renew to avoid service disruption.", ai_recommendation: "Renew certificate, implement automated renewal with Let's Encrypt", mitre_tactics: [], mitre_techniques: [], iocs: [], is_ai_triaged: false, tags: ["certificate", "maintenance"], occurred_at: ago(days(3)), created_at: ago(days(3)), updated_at: null,
  },
  {
    id: "alrt_025", tenant_id: "t1", title: "Successful login after 15 failed attempts", description: "User account logged in successfully after 15 failed attempts — possible successful brute force.", severity: "low", status: "false_positive", source: "siem", source_ref: "SIEM-9910", risk_score: 30, ai_summary: "Investigation revealed user forgot password. False positive confirmed.", ai_recommendation: "Closed — user confirmed via phone", mitre_tactics: [], mitre_techniques: [], iocs: [], is_ai_triaged: true, tags: ["false-positive"], occurred_at: ago(days(2)), created_at: ago(days(2)), updated_at: ago(days(1)),
  },
];

export const MOCK_INCIDENTS: (Incident & { alert_count: number })[] = [
  {
    id: "inc_001", tenant_id: "t1", title: "Ransomware Attack — Finance Department", description: "CryptoLocker variant deployed across finance shared drives. 3 workstations and 1 file server encrypted. Business operations impacted. IR team engaged.", severity: "critical", status: "open", category: "ransomware", risk_score: 97, ai_summary: "Active ransomware incident. Lateral movement confirmed from initial compromise via phishing email. Patient zero identified as WS-FIN-022.", attack_vector: "Phishing email with malicious Excel macro", business_impact: "Finance operations halted. Estimated 4-6 hours downtime. Backup restoration in progress.", remediation_steps: [{ priority: 1, action: "Isolate all affected hosts from network", rationale: "Prevent further encryption spread" }, { priority: 2, action: "Restore from last clean backup (48h ago)", rationale: "Fastest path to recovery" }, { priority: 3, action: "Rebuild affected workstations", rationale: "Ensure no persistence remains" }], mitre_attack_chain: { tactics: ["Initial Access", "Execution", "Persistence", "Impact"], techniques: [{ id: "T1566", name: "Phishing" }, { id: "T1486", name: "Data Encrypted for Impact" }], kill_chain_phase: "Actions on Objectives" }, affected_assets: ["WS-FIN-022", "WS-FIN-015", "WS-FIN-008", "FILESERVER01"], iocs: [{ type: "hash", value: "a1b2c3d4e5f6789012345678901234ab", context: "Ransomware binary" }], timeline: [{ timestamp: ago(hrs(2)), event: "First encryption detected on FILESERVER01", added_by: "EDR System" }, { timestamp: ago(hrs(1.5)), event: "IR team notified and engaged", added_by: "SOC L1" }, { timestamp: ago(hrs(1)), event: "Network isolation completed for 4 hosts", added_by: "admin" }], tags: ["ransomware", "p1", "active"], sla_breach: false, sla_deadline: new Date(Date.now() + hrs(6)).toISOString(), occurred_at: ago(hrs(2)), created_at: ago(hrs(2)), closed_at: null, alert_count: 3,
  },
  {
    id: "inc_002", tenant_id: "t1", title: "APT Campaign — Supply Chain Compromise Suspected", description: "Multiple indicators suggest nation-state threat actor targeting software development pipeline. Suspicious commits detected in internal repository.", severity: "critical", status: "investigating", category: "apt", risk_score: 94, ai_summary: "Sophisticated APT activity consistent with known threat actor TTPs. Long dwell time likely — assume full domain compromise.", attack_vector: "Compromised developer credentials via spearphishing", business_impact: "Potential IP theft, source code exfiltration risk, customer data at risk if trojanized builds shipped.", remediation_steps: [{ priority: 1, action: "Audit all commits in last 90 days", rationale: "Identify any trojanized code" }, { priority: 2, action: "Rotate all developer credentials and SSH keys", rationale: "Remove attacker access" }, { priority: 3, action: "Enable code signing for all builds", rationale: "Detect future tampering" }], mitre_attack_chain: { tactics: ["Initial Access", "Persistence", "Collection", "Exfiltration"], techniques: [{ id: "T1195", name: "Supply Chain Compromise" }, { id: "T1567", name: "Exfiltration Over Web Service" }], kill_chain_phase: "Collection" }, affected_assets: ["DEV-SERVER-01", "GIT-INTERNAL", "BUILD-PIPELINE"], iocs: [{ type: "domain", value: "update-windows-cdn.com", context: "C2" }, { type: "ip", value: "91.195.240.123", context: "Exfil destination" }], timeline: [{ timestamp: ago(days(5)), event: "Anomalous repository access detected", added_by: "SIEM" }, { timestamp: ago(days(4)), event: "Threat Intel correlation matched APT29 TTP", added_by: "Threat Intel" }, { timestamp: ago(days(3)), event: "Full IR investigation initiated", added_by: "CISO" }], tags: ["apt", "nation-state", "supply-chain"], sla_breach: false, sla_deadline: new Date(Date.now() + hrs(24)).toISOString(), occurred_at: ago(days(5)), created_at: ago(days(5)), closed_at: null, alert_count: 8,
  },
  {
    id: "inc_003", tenant_id: "t1", title: "Data Breach — Customer PII Exposed", description: "SQL injection vulnerability exploited on customer portal, resulting in unauthorized access to ~12,000 customer records including names, emails, and hashed passwords.", severity: "critical", status: "contained", category: "data_breach", risk_score: 89, ai_summary: "Data breach confirmed. Attacker accessed customer database via SQLi. Breach scope limited to 12,000 records. No financial data compromised.", attack_vector: "SQL injection on customer portal", business_impact: "GDPR notification required within 72 hours. Estimated regulatory fine risk: €500K-2M. Customer trust impact.", remediation_steps: [{ priority: 1, action: "Patch SQLi vulnerability immediately", rationale: "Close the attack vector" }, { priority: 2, action: "Force password reset for all affected customers", rationale: "Prevent credential stuffing attacks" }, { priority: 3, action: "Submit GDPR breach notification", rationale: "Legal requirement — 72h deadline" }], mitre_attack_chain: { tactics: ["Initial Access", "Credential Access", "Exfiltration"], techniques: [{ id: "T1190", name: "SQLi" }, { id: "T1552", name: "Unsecured Credentials" }], kill_chain_phase: "Exfiltration" }, affected_assets: ["PORTAL-WEB-01", "CUSTOMER-DB-01"], iocs: [{ type: "ip", value: "103.45.67.89", context: "Attacker IP" }], timeline: [{ timestamp: ago(days(1)), event: "SQLi attack detected by WAF", added_by: "WAF System" }, { timestamp: ago(hrs(22)), event: "Database access logs reviewed — 12K records accessed", added_by: "DBA Team" }, { timestamp: ago(hrs(20)), event: "Vulnerability patched, attacker access revoked", added_by: "Dev Team" }, { timestamp: ago(hrs(12)), event: "Legal team notified, GDPR process initiated", added_by: "CISO" }], tags: ["data-breach", "gdpr", "sqli"], sla_breach: false, sla_deadline: new Date(Date.now() + hrs(12)).toISOString(), occurred_at: ago(days(1)), created_at: ago(days(1)), closed_at: null, alert_count: 2,
  },
  {
    id: "inc_004", tenant_id: "t1", title: "Business Email Compromise — Wire Transfer Fraud", description: "CFO email account compromised. Attacker sent fraudulent wire transfer instructions to accounts payable, resulting in $75,000 transferred to attacker-controlled account.", severity: "high", status: "investigating", category: "phishing", risk_score: 82, ai_summary: "BEC attack resulted in financial loss. Account now secured. Working with bank for fund recovery.", attack_vector: "CEO spearphishing → CFO account compromise → AP manipulation", business_impact: "$75,000 financial loss. Bank recall initiated with 60% success probability.", remediation_steps: [{ priority: 1, action: "Contact bank immediately for wire recall", rationale: "Time-sensitive — higher chance within 24h" }, { priority: 2, action: "Enable MFA for all C-suite accounts", rationale: "Prevent recurrence" }, { priority: 3, action: "Train AP team on BEC recognition", rationale: "Human layer defense" }], mitre_attack_chain: { tactics: ["Initial Access", "Social Engineering"], techniques: [{ id: "T1566", name: "Spearphishing" }, { id: "T1078", name: "Valid Accounts" }], kill_chain_phase: "Actions on Objectives" }, affected_assets: ["CFO-MAILBOX", "AP-WORKSTATION"], iocs: [{ type: "email", value: "cfo@company-corp.com", context: "Spoofed domain" }], timeline: [{ timestamp: ago(hrs(36)), event: "Fraudulent wire transfer request sent to AP", added_by: "Email System" }, { timestamp: ago(hrs(34)), event: "Wire transfer executed — $75,000", added_by: "AP Team" }, { timestamp: ago(hrs(28)), event: "Fraud detected during daily reconciliation", added_by: "Finance" }, { timestamp: ago(hrs(27)), event: "Bank notified, recall initiated", added_by: "CFO" }], tags: ["bec", "financial-fraud", "phishing"], sla_breach: true, sla_deadline: new Date(Date.now() - hrs(4)).toISOString(), occurred_at: ago(hrs(36)), created_at: ago(hrs(36)), closed_at: null, alert_count: 1,
  },
  {
    id: "inc_005", tenant_id: "t1", title: "Insider Threat — HR Data Exfiltration", description: "Departing employee bulk-downloaded HR system records containing all 847 employee records 48 hours before resignation. Suspected sale to competitor.", severity: "high", status: "investigating", category: "insider_threat", risk_score: 78, ai_summary: "Confirmed insider threat with data exfiltration. Legal hold placed on all evidence. Investigation ongoing.", attack_vector: "Authorized access misused — excessive bulk download", business_impact: "Employee PII exposed. Trade secret risk. Legal action likely.", remediation_steps: [{ priority: 1, action: "Preserve all digital evidence under legal hold", rationale: "Required for prosecution" }, { priority: 2, action: "Revoke all system access immediately", rationale: "Prevent further exfiltration" }, { priority: 3, action: "Engage legal counsel and HR", rationale: "Employee termination and potential prosecution" }], mitre_attack_chain: { tactics: ["Collection", "Exfiltration"], techniques: [{ id: "T1074", name: "Data Staged" }, { id: "T1567", name: "Exfiltration Over Web Service" }], kill_chain_phase: "Exfiltration" }, affected_assets: ["HR-SYSTEM-01", "SHAREPOINT-HR"], iocs: [], timeline: [{ timestamp: ago(days(2)), event: "Bulk download of 847 employee records", added_by: "UEBA System" }, { timestamp: ago(days(1)), event: "Resignation letter received by HR", added_by: "HR" }, { timestamp: ago(hrs(18)), event: "UEBA alert correlated with resignation", added_by: "SOC L2" }, { timestamp: ago(hrs(16)), event: "Legal hold placed, investigation opened", added_by: "Legal" }], tags: ["insider-threat", "hr-data", "ueba"], sla_breach: false, sla_deadline: new Date(Date.now() + days(1)).toISOString(), occurred_at: ago(days(2)), created_at: ago(hrs(18)), closed_at: null, alert_count: 1,
  },
];

export const MOCK_PHISHING: (PhishingSubmission & { subject?: string; sender?: string })[] = [
  { id: "ph_001", verdict: "phishing", status: "completed", confidence_score: 0.97, risk_score: 96, ai_analysis: "High-confidence phishing email. Contains credential harvesting link disguised as Microsoft 365 login page. Domain registered 2 days ago. Multiple phishing indicators present.", phishing_indicators: [{ type: "domain_age", description: "Domain registered less than 7 days ago", severity: "high" }, { type: "credential_harvesting", description: "Fake login form detected at destination URL", severity: "high" }, { type: "urgency", description: "Social engineering urgency language detected", severity: "medium" }], extracted_urls: ["http://microsoftf-365-login.com/auth"], iocs: [{ type: "domain", value: "microsoftf-365-login.com", context: "Phishing domain" }, { type: "ip", value: "185.234.219.11", context: "Hosting IP" }], header_analysis: { spf: "FAIL", dkim: "NONE", dmarc: "FAIL" }, spf_dkim_dmarc: { spf: "FAIL", dkim: "NONE", dmarc: "FAIL" }, url_scan_results: {}, created_at: ago(hrs(1)), subject: "Urgent: Your account will be suspended", sender: "security@microsoft-support-team.com" },
  { id: "ph_002", verdict: "phishing", status: "completed", confidence_score: 0.94, risk_score: 91, ai_analysis: "CEO fraud / BEC attempt. Lookalike domain targeting wire transfer from finance team.", phishing_indicators: [{ type: "lookalike_domain", description: "Homoglyph domain mimicking company name", severity: "high" }, { type: "financial_fraud", description: "Wire transfer request pattern", severity: "high" }], extracted_urls: ["https://secure-payroll.company-corp.com/transfer"], iocs: [{ type: "domain", value: "company-corp.com", context: "Lookalike domain" }], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "FAIL", dmarc: "FAIL" }, url_scan_results: {}, created_at: ago(hrs(3)), subject: "Urgent wire transfer required - CEO", sender: "ceo@company-corp.com" },
  { id: "ph_003", verdict: "suspicious", status: "completed", confidence_score: 0.71, risk_score: 62, ai_analysis: "Suspicious email with some phishing indicators but inconclusive. Manual review recommended.", phishing_indicators: [{ type: "unusual_sender", description: "Sender domain doesn't match display name", severity: "medium" }, { type: "obfuscated_url", description: "URL uses redirect chain to hide destination", severity: "medium" }], extracted_urls: ["https://bit.ly/3xR9kPq"], iocs: [{ type: "url", value: "https://bit.ly/3xR9kPq", context: "Obfuscated redirect" }], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "PASS", dmarc: "NONE" }, url_scan_results: {}, created_at: ago(hrs(5)), subject: "Invoice #INV-2024-1157 attached", sender: "billing@invoices-system.net" },
  { id: "ph_004", verdict: "clean", status: "completed", confidence_score: 0.92, risk_score: 8, ai_analysis: "Legitimate email from trusted sender. All authentication checks pass. No malicious indicators.", phishing_indicators: [], extracted_urls: ["https://microsoft.com/en-us/security"], iocs: [], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "PASS", dmarc: "PASS" }, url_scan_results: {}, created_at: ago(hrs(8)), subject: "Microsoft Security Update Advisory", sender: "security@microsoft.com" },
  { id: "ph_005", verdict: "phishing", status: "completed", confidence_score: 0.99, risk_score: 98, ai_analysis: "Highly sophisticated spearphishing targeting IT admin. Contains valid-looking SSL cert and custom domain. Malware payload in attachment.", phishing_indicators: [{ type: "malware_attachment", description: "PDF contains embedded JavaScript dropper", severity: "high" }, { type: "credential_harvesting", description: "Fake VPN portal login page", severity: "high" }], extracted_urls: ["https://corp-vpn-portal.com/login"], iocs: [{ type: "domain", value: "corp-vpn-portal.com", context: "Phishing domain" }, { type: "hash", value: "aabb1122ccdd3344eeff5566778899aa", context: "PDF malware" }], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "PASS", dmarc: "FAIL" }, url_scan_results: {}, created_at: ago(hrs(12)), subject: "VPN Certificate Update Required", sender: "it-support@corp-helpdesk.com" },
  { id: "ph_006", verdict: "suspicious", status: "analyzing", confidence_score: 0.55, risk_score: 48, ai_analysis: "Analysis in progress...", phishing_indicators: [], extracted_urls: [], iocs: [], header_analysis: {}, spf_dkim_dmarc: { spf: "NONE", dkim: "NONE", dmarc: "NONE" }, url_scan_results: {}, created_at: ago(mins(20)), subject: "Package delivery notification", sender: "delivery@fedex-notification.com" },
  { id: "ph_007", verdict: "phishing", status: "completed", confidence_score: 0.88, risk_score: 84, ai_analysis: "HR-themed phishing targeting employee credentials with fake benefits portal.", phishing_indicators: [{ type: "fake_portal", description: "Fake HR benefits login page", severity: "high" }], extracted_urls: ["https://hr-benefits-portal.employees-self-service.com/login"], iocs: [{ type: "domain", value: "employees-self-service.com", context: "Phishing domain" }], header_analysis: {}, spf_dkim_dmarc: { spf: "FAIL", dkim: "NONE", dmarc: "FAIL" }, url_scan_results: {}, created_at: ago(days(1)), subject: "Action required: Update your benefits by Friday", sender: "hr@employees-self-service.com" },
  { id: "ph_008", verdict: "clean", status: "completed", confidence_score: 0.96, risk_score: 5, ai_analysis: "Legitimate marketing email from known vendor. Unsubscribe link verified as legitimate.", phishing_indicators: [], extracted_urls: ["https://salesforce.com/products"], iocs: [], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "PASS", dmarc: "PASS" }, url_scan_results: {}, created_at: ago(days(1)), subject: "Your Salesforce renewal is coming up", sender: "renewal@salesforce.com" },
  { id: "ph_009", verdict: "suspicious", status: "completed", confidence_score: 0.68, risk_score: 55, ai_analysis: "Email contains moderately suspicious characteristics. Could be spam or low-sophistication phishing.", phishing_indicators: [{ type: "urgency", description: "Urgency language around account expiry", severity: "low" }, { type: "grammar_errors", description: "Multiple grammatical errors typical of non-native English", severity: "low" }], extracted_urls: ["http://account-verify-now.com/verify"], iocs: [{ type: "domain", value: "account-verify-now.com", context: "Suspicious domain" }], header_analysis: {}, spf_dkim_dmarc: { spf: "FAIL", dkim: "NONE", dmarc: "NONE" }, url_scan_results: {}, created_at: ago(days(2)), subject: "Your account will be closed in 24 hours", sender: "no-reply@account-verify-now.com" },
  { id: "ph_010", verdict: "phishing", status: "completed", confidence_score: 0.96, risk_score: 95, ai_analysis: "IRS tax refund phishing scam. Classic social engineering targeting financial credentials.", phishing_indicators: [{ type: "impersonation", description: "Impersonating IRS government agency", severity: "high" }, { type: "credential_harvesting", description: "Fake tax portal requesting SSN and bank details", severity: "high" }], extracted_urls: ["https://irs-refund-2024.com/claim"], iocs: [{ type: "domain", value: "irs-refund-2024.com", context: "Phishing domain" }], header_analysis: {}, spf_dkim_dmarc: { spf: "FAIL", dkim: "NONE", dmarc: "FAIL" }, url_scan_results: {}, created_at: ago(days(2)), subject: "Tax Refund $2,840 Pending — Verify to Claim", sender: "refunds@irs-gov-2024.com" },
  { id: "ph_011", verdict: "clean", status: "completed", confidence_score: 0.98, risk_score: 3, ai_analysis: "Legitimate internal email from verified sender. No external links or attachments.", phishing_indicators: [], extracted_urls: [], iocs: [], header_analysis: {}, spf_dkim_dmarc: { spf: "PASS", dkim: "PASS", dmarc: "PASS" }, url_scan_results: {}, created_at: ago(days(3)), subject: "Q4 Security Awareness Training Reminder", sender: "security@company.com" },
  { id: "ph_012", verdict: "suspicious", status: "pending", confidence_score: 0, risk_score: 0, ai_analysis: "Queued for analysis.", phishing_indicators: [], extracted_urls: [], iocs: [], header_analysis: {}, spf_dkim_dmarc: { spf: "NONE", dkim: "NONE", dmarc: "NONE" }, url_scan_results: {}, created_at: ago(mins(5)), subject: "Cryptocurrency investment opportunity", sender: "invest@crypto-gains-now.com" },
];

export const MOCK_REPORTS: Report[] = [
  { id: "rpt_001", title: "Q4 2024 Executive Security Summary", report_type: "executive_summary", status: "completed", period_start: ago(days(90)), period_end: ago(days(1)), content: {}, ai_narrative: "During Q4 2024, the organization experienced 2,847 security alerts, a 23% increase from Q3. Critical incidents declined by 15%, indicating improving detection and response capabilities. Mean Time to Detect (MTTD) improved from 4.2 hours to 2.8 hours. Three major incidents were fully contained with no data loss. Recommended focus areas: cloud security posture, MFA rollout completion, and insider threat program expansion.", metrics: { total_alerts: 2847, critical_incidents: 3, mttd_hours: 2.8, mttr_hours: 6.4 }, pdf_path: "/reports/q4-2024-executive.pdf", created_at: ago(days(7)) },
  { id: "rpt_002", title: "Ransomware Incident — Full Investigation Report", report_type: "incident_report", status: "completed", period_start: ago(hrs(72)), period_end: ago(hrs(2)), content: {}, ai_narrative: "The ransomware incident began with a phishing email containing a malicious Excel macro, delivered to the Finance department. Patient zero identified as WS-FIN-022. The malware established persistence via scheduled task and began lateral movement using stolen credentials. File encryption commenced 6 hours after initial compromise. Total downtime: 4.5 hours. No data was exfiltrated before detection. Full remediation completed with clean backup restoration.", metrics: { hosts_affected: 4, data_encrypted_gb: 156, recovery_time_hours: 4.5, total_cost_usd: 45000 }, pdf_path: "/reports/ransomware-inc-001.pdf", created_at: ago(days(1)) },
  { id: "rpt_003", title: "Weekly Threat Intelligence Report — Week 50", report_type: "weekly", status: "completed", period_start: ago(days(7)), period_end: new Date().toISOString(), content: {}, ai_narrative: "This week's threat landscape was dominated by a surge in Cobalt Strike-related activity targeting financial sector organizations. Three new CVEs of critical severity were disclosed affecting Apache, OpenSSL, and Windows kernel. Phishing volumes increased 34% globally. Recommended immediate actions: patch OpenSSL CVE-2024-5535, review Cobalt Strike detection rules, and update email filtering for new phishing templates.", metrics: { new_threats: 12, critical_cves: 3, phishing_increase_pct: 34 }, pdf_path: "/reports/weekly-w50-2024.pdf", created_at: ago(days(2)) },
  { id: "rpt_004", title: "Compliance Audit Report — ISO 27001", report_type: "compliance", status: "completed", period_start: ago(days(30)), period_end: ago(days(1)), content: {}, ai_narrative: "ISO 27001 compliance audit for the current period shows 87% control effectiveness, up from 82% last quarter. Key gaps identified: (1) Privileged access review not completed for 3 service accounts, (2) Business continuity test overdue by 14 days, (3) Security awareness training completion at 78% (target: 95%). Remediation plan required for Annex A.9 controls.", metrics: { compliance_score: 87, gaps_identified: 3, controls_passed: 109, controls_failed: 16 }, pdf_path: "/reports/iso27001-audit-2024.pdf", created_at: ago(days(5)) },
  { id: "rpt_005", title: "Monthly Security Metrics — November 2024", report_type: "monthly", status: "generating", period_start: ago(days(30)), period_end: new Date().toISOString(), content: {}, ai_narrative: null, metrics: {}, pdf_path: null, created_at: ago(mins(15)) },
];

export const MOCK_STATS: DashboardStats = {
  total_alerts: 2847,
  new_alerts: 23,
  critical_alerts: 7,
  open_incidents: 4,
  phishing_today: 12,
  confirmed_phishing: 3,
  alerts_this_week: 156,
  as_of: new Date().toISOString(),
};

export const MOCK_TREND = Array.from({ length: 30 }, (_, i) => {
  const d = new Date(Date.now() - (29 - i) * days(1));
  const base = 80 + Math.sin(i * 0.4) * 30 + Math.random() * 20;
  return {
    date: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
    count: Math.round(base),
  };
});

export const MOCK_SEVERITY_DIST: Record<string, number> = {
  critical: 45,
  high: 120,
  medium: 280,
  low: 350,
  info: 89,
};

export const MOCK_ACTIVITY = [
  { type: "alert", id: "alrt_019", title: "DLL side-loading on finance workstation", severity: "critical", created_at: ago(mins(20)) },
  { type: "alert", id: "alrt_004", title: "Brute force attack on VPN concentrator", severity: "high", created_at: ago(hrs(1)) },
  { type: "incident", id: "inc_001", title: "Ransomware Attack — Finance Department", severity: "critical", created_at: ago(hrs(2)) },
  { type: "alert", id: "alrt_006", title: "Suspicious PowerShell encoded command", severity: "high", created_at: ago(mins(45)) },
  { type: "alert", id: "alrt_009", title: "Phishing email campaign — executive impersonation", severity: "high", created_at: ago(mins(90)) },
  { type: "incident", id: "inc_004", title: "Business Email Compromise — Wire Transfer", severity: "high", created_at: ago(hrs(36)) },
  { type: "alert", id: "alrt_020", title: "Kerberoasting attack detected", severity: "high", created_at: ago(mins(60)) },
  { type: "alert", id: "alrt_022", title: "Domain admin created outside change window", severity: "critical", created_at: ago(hrs(18)) },
];

export const MOCK_AUDIT_LOGS = Array.from({ length: 50 }, (_, i) => {
  const actions = ["LOGIN_SUCCESS", "ALERT_UPDATED", "INCIDENT_CREATED", "REPORT_GENERATED", "USER_LOGOUT", "TRIAGE_STARTED", "PLAYBOOK_EXECUTED", "SETTINGS_CHANGED", "ALERT_RESOLVED", "INCIDENT_CLOSED"];
  const users = ["admin", "analyst1", "soc_manager", "john.doe", "jane.smith"];
  const resources = ["Alert #alrt_00" + (i % 9 + 1), "Incident #inc_00" + (i % 5 + 1), "Report #rpt_001", "User Settings", "Playbook #PB-03"];
  return {
    id: `log_${String(i + 1).padStart(3, "0")}`,
    user: users[i % users.length],
    action: actions[i % actions.length],
    resource: resources[i % resources.length],
    ip_address: `10.0.${Math.floor(i / 10)}.${(i % 10) + 1}`,
    status: i % 10 === 7 ? "FAILED" : "SUCCESS",
    created_at: ago((50 - i) * mins(30)),
  };
});

export function generateMockAIResponse(userMessage: string): string {
  const msg = userMessage.toLowerCase();
  if (msg.includes("ransomware")) return `## Ransomware Response Analysis\n\n**Threat Assessment:** High Severity — Immediate Action Required\n\n### Immediate Containment Steps\n1. **Isolate affected systems** from the network immediately (pull ethernet, disable WiFi)\n2. **Do NOT reboot** affected machines — preserve encrypted file headers for recovery\n3. **Preserve volatile memory** with a memory dump if possible\n4. **Identify patient zero** — trace the infection vector via EDR telemetry\n\n### Identification\n- Check file extension changes (e.g., \`.locked\`, \`.encrypted\`, \`.CRYPTED\`)\n- Look for ransom note files (README.txt, HOW_TO_DECRYPT.html)\n- Check for known ransomware families via hash lookup on VirusTotal\n\n### Recovery Strategy\n- **Do NOT pay the ransom** unless all other options are exhausted\n- Restore from last known clean backup\n- If no backup: check for Volume Shadow Copies (\`vssadmin list shadows\`)\n\n### MITRE ATT&CK\n- T1486: Data Encrypted for Impact\n- T1490: Inhibit System Recovery\n\n> **Always engage your IR team and legal counsel before any public communications.**`;

  if (msg.includes("phishing") || msg.includes("bec")) return `## Phishing / BEC Analysis\n\n**Key Indicators to Check:**\n\n| Indicator | What to Look For |\n|-----------|------------------|\n| Sender Domain | Lookalike domains (company-c0rp.com vs company-corp.com) |\n| Reply-To | Different from From: address |\n| Urgency | "Act immediately", "Within 24 hours" |\n| Links | Hover before clicking, use URLScan.io |\n| Attachments | Office macros, .exe disguised as PDF |\n\n### Email Header Analysis\n\`\`\`\nReturn-Path: <attacker@evil.com>   ← Check this!\nReceived: from spoofed.domain\nX-Originating-IP: 185.220.101.47  ← Look up in threat intel\n\`\`\`\n\n### For BEC (Business Email Compromise)\n- **Immediately contact your bank** if a fraudulent wire was initiated\n- Fund recall is most effective within the first 24 hours\n- Preserve all email evidence for law enforcement\n\n### MITRE ATT&CK\n- T1566.001: Spearphishing Attachment\n- T1566.002: Spearphishing Link\n- T1534: Internal Spearphishing`;

  if (msg.match(/ioc|ip address|hash|domain|url/)) return `## IOC Analysis\n\nI can help analyze this indicator of compromise.\n\n### Recommended Analysis Steps\n\n**For IP Addresses:**\n\`\`\`bash\n# Check threat intel feeds\ncurl https://otx.alienvault.com/api/v1/indicators/IPv4/{ip}/general\n\n# Passive DNS lookup\ndig -x <IP>\n\n# ASN/Geolocation\nwhois <IP>\n\`\`\`\n\n**For File Hashes (MD5/SHA256):**\n- VirusTotal: \`https://www.virustotal.com/gui/file/{hash}\`\n- MalwareBazaar: \`https://bazaar.abuse.ch/sample/{hash}\`\n- Hybrid Analysis: Submit for full sandbox detonation\n\n**For Domains:**\n- Check domain registration date (new domains = higher risk)\n- Passive DNS to find historically associated IPs\n- Check against URLhaus, PhishTank, SURBL\n\n**Threat Intelligence Platforms:**\n- AlienVault OTX (free)\n- MISP (self-hosted)\n- Recorded Future (commercial)\n- Shodan for internet-exposed assets\n\n> IOCs have short lifespans — always check multiple feeds for freshness.`;

  if (msg.includes("mitre") || msg.includes("att&ck") || msg.includes("ttp")) return `## MITRE ATT&CK Framework\n\nMITRE ATT&CK is a globally accessible knowledge base of adversary tactics and techniques.\n\n### The 14 Tactics (Enterprise)\n\n| # | Tactic | Description |\n|---|--------|-------------|\n| 1 | Reconnaissance | Info gathering before attack |\n| 2 | Resource Development | Establishing attack infrastructure |\n| 3 | Initial Access | Gaining foothold |\n| 4 | Execution | Running malicious code |\n| 5 | Persistence | Maintaining foothold |\n| 6 | Privilege Escalation | Gaining higher permissions |\n| 7 | Defense Evasion | Avoiding detection |\n| 8 | Credential Access | Stealing credentials |\n| 9 | Discovery | Exploring the environment |\n| 10 | Lateral Movement | Moving through the network |\n| 11 | Collection | Gathering target data |\n| 12 | Command & Control | Communicating with implants |\n| 13 | Exfiltration | Stealing data out |\n| 14 | Impact | Manipulate, disrupt, destroy |\n\n### Practical Usage\n- Map your detections to MITRE techniques for coverage analysis\n- Use ATT&CK Navigator for heat-map visualization\n- Build detection rules around specific technique signatures\n\n> **Tip:** Start with T1059 (Command Scripting) and T1566 (Phishing) — the most common entry points.`;

  if (msg.includes("lateral movement") || msg.includes("smb") || msg.includes("rdp")) return `## Lateral Movement Detection\n\nLateral movement is when an attacker pivots from an initial compromised host to other systems.\n\n### Common Techniques\n\n\`\`\`\nT1021.001  Remote Desktop Protocol (RDP)\nT1021.002  SMB/Windows Admin Shares\nT1021.006  Windows Remote Management (WinRM)\nT1550.002  Pass the Hash\nT1550.003  Pass the Ticket (Kerberos)\nT1558.003  Kerberoasting\n\`\`\`\n\n### Detection Signals\n- **Unusual authentication**: Admin logins from non-admin workstations\n- **SMB tree connects**: To ADMIN$, C$, IPC$ shares\n- **Scheduled tasks**: Remotely created on other hosts\n- **WMI activity**: Remote WMI execution (wmiprvse.exe spawning processes)\n- **Service installation**: New services created remotely\n\n### Splunk Detection Query\n\`\`\`spl\nindex=windows EventCode=4624 LogonType=3\n| stats count by src_ip, dest_ip, user\n| where count > 10\n| sort -count\n\`\`\`\n\n### Prevention\n- Implement network segmentation and micro-segmentation\n- Disable NTLM authentication where possible\n- Enable Windows Defender Credential Guard\n- Use tiered admin model (separate admin accounts per tier)`;

  if (msg.includes("incident") && (msg.includes("response") || msg.includes("playbook"))) return `## Incident Response Playbook\n\n### The 6 Phases of IR (NIST SP 800-61)\n\n**Phase 1: Preparation**\n- Maintain updated asset inventory\n- Keep IR tools ready (Volatility, FTK Imager, Wireshark)\n- Ensure legal/PR contacts are accessible\n- Test backup restoration procedures\n\n**Phase 2: Detection & Analysis**\n- Correlate alerts in SIEM\n- Determine scope: which systems, users, data affected?\n- Assign severity (P1-P4) and incident commander\n- Open incident ticket and war room\n\n**Phase 3: Containment**\n- Short-term: Isolate affected hosts from network\n- Long-term: Apply patches, change credentials, block IOCs\n- Preserve forensic evidence BEFORE containment where possible\n\n**Phase 4: Eradication**\n- Remove malware, close initial access vector\n- Rebuild affected systems from clean images\n- Verify no persistence mechanisms remain\n\n**Phase 5: Recovery**\n- Restore from verified clean backups\n- Monitor closely for 30 days post-incident\n- Verify business operations back to normal\n\n**Phase 6: Post-Incident**\n- Write detailed incident report within 72h\n- Conduct blameless post-mortem\n- Update detection rules and playbooks\n- Share threat intel with ISAC/sector peers\n\n> **Golden Rule:** Log everything, preserve everything, assume breach is ongoing until proven otherwise.`;

  if (msg.includes("playbook") || msg.includes("malware containment")) return `## Malware Containment Playbook\n\n### Trigger Conditions\n- EDR alert with malware detection\n- Unusual process spawning or network activity\n- Multiple hosts showing similar indicators\n\n### Step-by-Step Response\n\n\`\`\`\n[T+0:00]  Alert received → Assign to L2 analyst\n[T+0:05]  Verify alert — check EDR console for process tree\n[T+0:10]  Assess blast radius — is it spreading?\n[T+0:15]  CONTAIN — Network isolate affected host(s)\n[T+0:20]  EVIDENCE — Capture memory dump + disk image\n[T+0:30]  ANALYZE — Submit sample to sandbox (JoeSandbox/Cuckoo)\n[T+1:00]  ERADICATE — Remove malware, check for persistence\n[T+2:00]  RECOVER — Restore from backup or rebuild\n[T+4:00]  VERIFY — Confirm clean, monitor for 24h\n[T+24:00] POST-INCIDENT — Write report, update rules\n\`\`\`\n\n### Containment Commands\n\`\`\`powershell\n# Isolate host via PowerShell (if EDR not available)\nNew-NetFirewallRule -DisplayName \"BLOCK_ALL\" -Direction Inbound -Action Block\nNew-NetFirewallRule -DisplayName \"BLOCK_ALL_OUT\" -Direction Outbound -Action Block\n\n# Collect volatile data before isolation\nGet-Process | Export-Csv processes.csv\nGet-NetTCPConnection | Export-Csv connections.csv\n\`\`\``;

  if (msg.includes("cve") || msg.includes("vulnerability") || msg.includes("patch")) return `## Vulnerability Management\n\n### CVE Severity Scoring (CVSS v3)\n\n| Score | Severity | Action |\n|-------|----------|--------|\n| 9.0-10.0 | Critical | Patch within 24-48 hours |\n| 7.0-8.9 | High | Patch within 7 days |\n| 4.0-6.9 | Medium | Patch within 30 days |\n| 0.1-3.9 | Low | Patch within 90 days |\n\n### Prioritization Framework\nNot all CVEs are equal. Consider:\n1. **CVSS Score** — Base severity\n2. **EPSS Score** — Probability of exploitation in the wild\n3. **Asset criticality** — Is the vulnerable system internet-facing?\n4. **Threat intel** — Is it being actively exploited?\n5. **CISA KEV** — Is it on CISA's Known Exploited Vulnerabilities catalog?\n\n### Useful Tools\n- **Tenable Nessus / Qualys** — Vulnerability scanning\n- **Shodan** — Find internet-exposed vulnerable systems\n- **CISA KEV Catalog** — \`https://www.cisa.gov/kev\`\n- **NVD** — \`https://nvd.nist.gov\`\n\n> **Pro tip:** Focus on CISA KEV + high EPSS score first — these are being actively exploited.`;

  return `## SOC AI Assistant Response\n\nThank you for your query. Based on my security knowledge base, here's what I can provide:\n\n### Analysis\nYour question touches on an important security operations topic. Let me provide context and actionable guidance.\n\n**Key Considerations:**\n- Verify all alerts in context before taking action\n- Follow your organization's incident response procedures\n- Preserve evidence before remediation\n- Escalate high-severity findings immediately\n\n**Recommended Next Steps:**\n1. Cross-reference with your threat intelligence feeds\n2. Check MITRE ATT&CK for related techniques\n3. Review historical alerts for similar patterns\n4. Consult your playbook library for step-by-step guidance\n\n**Useful Resources:**\n- MITRE ATT&CK: https://attack.mitre.org\n- CISA Alerts: https://www.cisa.gov/news-events/cybersecurity-advisories\n- NIST Cybersecurity Framework: https://www.nist.gov/cyberframework\n\n> *Ask me about specific threats, IOC analysis, incident response procedures, MITRE techniques, or vulnerability management.*`;
}
